/** The icons the app uses, named for the job rather than the glyph. */
export enum IconName {
  Back = "back",
  Forward = "forward",
  Settings = "settings",
  Minimize = "minimize",
  Maximize = "maximize",
  Restore = "restore",
  Close = "close",
  Start = "start",
  Stop = "stop",
  Refresh = "refresh",
  Search = "search",
  OpenLink = "open-link",
  Clear = "clear",
  Copy = "copy",
  CopyUrlEncoded = "copy-url-encoded",
  Success = "success",
  CollapseRail = "collapse-rail",
  ExpandRail = "expand-rail",
  Supergraph = "supergraph",
  Database = "database",
}
